apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-cpf-config-map
  namespace: {{.Release.Namespace}}

data:

    data.cpf: | 
        [Startup]
        SystemMode=TEST
        
        [config]
        globals=0,0,256,0,0,0

        [Actions]
        CreateNamespace:Name=SDS,Globals=iriscluster,Routines=iriscluster,Interop=1
        CreateMapPackage:Namespace=SDS,Name=SDS,Database=isccode
        CreateMapPackage:Namespace=SDS,Name=SDSTest,Database=isccode
        CreateMapPackage:Namespace=SDS,Name=intersystems,Database=isccode
        CreateMapPackage:Namespace=SDS,Name=IRISConfig,Database=isccode
        CreateMapPackage:Namespace=SDS,Name=ML,Database=isccode
        CreateMapRoutine:Namespace=SDS,Name=ZSTU,Database=isccode
        CreateMapRoutine:Namespace=SDS,Name=SDSMACROS,Database=isccode

    compute.cpf: | 
        [Startup]
        SystemMode=TEST
        
        [config]
        globals=0,0,256,0,0,0
