{{- if eq (toString .Values.consumer.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: persister-iris
  namespace: {{.Release.Name}}
  annotations:
    sds/load-ports-as-separate-services: "true"
  labels:
    app: persister-iris
spec:
  selector:
    intersystems.com/component: data
    intersystems.com/kind: IrisCluster
    intersystems.com/role: iris
  ports:
    - name: persister-iris
      port: {{ .Values.consumer.port }}
      targetPort: 8081
  type: LoadBalancer
{{- end }}