{{- if eq (toString .Values.management.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: connectors-java
  namespace: {{.Release.Name}}
  labels:
    app: connectors-java
spec:
  selector:
    app: connectors-java
  ports:
    - name: management
      port: {{ .Values.management.port }}
      targetPort: 8000
    - name: quickfix
      port: {{ .Values.quickfix.port }}
      targetPort: 3001
  type: LoadBalancer
{{- end }}