apiVersion: apps/v1
kind: Deployment
metadata:
  name: morningstar-producer
  namespace: {{.Release.Name}}
  labels:
    app: morningstar-producer


spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: morningstar-producer
  template:
    metadata:
      labels:
        app: morningstar-producer
    spec:
      # imagePullSecrets:
      #   - name: intersystems-container-registry-secret
      imagePullSecrets:
        {{- if .Values.requiredSecrets.intersystemsContainerRegistrySecret }}
        - name: {{ .Values.requiredSecrets.intersystemsContainerRegistrySecret }}
        {{- end }}
      containers:
        - name: morningstar-producer
          image: {{ .Values.image.registry }}/{{ .Values.image.producer.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            requests:
              cpu: {{ .Values.compute.database.cpu }}
              memory: {{ .Values.compute.database.memory }}
          # ports:
          #   - name: management
          #     containerPort: 8000
        env:
        - name: CLOUD_PROVIDER
          value: {{ .Values.cloudProvider }}
        - name: CLOUD_PROVIDER_REGION
          value: {{ .Values.cloudProviderRegion }}
        - name: SERVICE_INTERNAL_NAME
          value: {{ .Values.serviceInternalName }}
        - name: KAFKA_BROKER
          value: {{ .Values.kafkaBroker }}
      {{- if .Values.compute.database.nodeTypeSelector }}
      nodeSelector:
        sds/node-type: {{ .Values.compute.database.nodeTypeSelector }}
      {{- end }}
      tolerations:
        - key: sds/select-worker
          value: select-worker
          effect: NoSchedule
